site_name: 0xkb · knowledge base
site_url: https://0xkb.n0signal.dev/

theme:
  name: dracula
  sidebar: true
  navigation_depth: 2
  components:
    footer: false
    title: false
  favicon: assets/favicon.ico
  logo: assets/logo.png
        
markdown_extensions:
  - admonition
  - nl2br 
  - toc:
      permalink: false

plugins:
  - search
  - awesome-pages
      
extra_css:
  - assets/heading-fix.css
  - assets/blacksite.css

extra_javascript:
  - assets/logo-link.js
